name: Test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: Run RuboCop
        run: |
          bundle install
          bundle exec rubocop

  test:
    needs: lint
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            cc: gcc
          - runs-on: macos-14
            cc: gcc-14
          - runs-on: windows-latest
            cc: gcc
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Run build and tests
        env:
          CC: ${{ matrix.cc }}
        run: |
          DEBUG=
          if [ "$RUNNER_DEBUG" = "1" ]; then
            DEBUG="--verbose"
          fi
          rake $DEBUG all test

      - name: Memory Leak Check
        if: matrix.runs-on == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y valgrind
          rake test:memcheck
